version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=development

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appspot
      MYSQL_USER: appspot
      MYSQL_PASSWORD: appspot123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/database/schema:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
